### ISSUE TITLE
Checklist for Addition of words in Santali Open Dictionary, Glossary

### ISSUE THREAD

**Issue by Prasanta-Hembram** [Prasanta-Hembram/Translation-work-list-for-Santali-language#9]
These are some targets to be completed in the coming days:
- [x] Common General Words(Human Body parts, Color, Eatables Names)
- [ ] World Country Name
- [ ] Indian States Name
- [ ] Proper names
